name: Flutter

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
  
      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v4.0
        with:
          version: latest
          channel: stable

      - name: Build for Android
        run: flutter build apk --split-per-abi

      - name: Upload Android Build
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/*.apk

      - name: Install Linux dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

      - name: Build for Linux
        run: flutter build linux

      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux/x64/release/bundle/*
        
